controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:
    path: /auth/login
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path:       /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
